/**********************************************************************************************************************
 * \file ADC_Queued_Scan.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ADC_QUEUED_SCAN_H_
#define ADC_QUEUED_SCAN_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Ifx_Types.h"
#include "IfxDma_Dma.h"
#include "IfxEvadc_Adc.h"


#define DMA_CHANNEL              0
#define N_TRANSFER               8
#define ISR_PRIORITY_DMA         20
#define DEST_ADDR                0x70000000
#define SRC_ADDR                 0xF0021304
#define NO_OPTIONS               0
#define GROUPID_3          IfxEvadc_GroupId_3                  /* EVADC group                                      */
#define CHANNELS_NUM       5                                   /* Number of used channels                          */
#define AN25_CHID          1                                   /* Channel ID for pin AN33                          */
#define AN26_CHID          2                                   /* Channel ID for pin AN39                          */
#define AN27_CHID          3                                   /* Channel ID for pin AN44                          */
#define AN28_CHID          4                                   /* Channel ID for pin AN44                          */
#define AN29_CHID          5                                   /* Channel ID for pin AN44                          */
#define AN30_CHID          6                                   /* Channel ID for pin AN33                          */
#define AN31_CHID          7                                   /* Channel ID for pin AN39                          */
#define AN32_CHID          8                                   /* Channel ID for pin AN44                          */


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initEVADC(void);
void readEVADC(void);
void init_DMA(void);


#endif /* ADC_QUEUED_SCAN_H_ */
